spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:./h2db/kardex
    driverClassName: org.h2.Driver
    username: lunch
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8080